---

format:
  _help_max_lines_hwrap:
    - If a candidate layout is wrapped horizontally but it exceeds
    - this many lines, then reject the layout.
  max_lines_hwrap: 2
  _help_keyword_case:
    - Format keywords consistently as 'lower' or 'upper' case
  keyword_case: uppet
  _help_max_subgroups_hwrap:
    - If an argument group contains more than this many sub-groups
    - (parg or kwarg groups) then force it to a vertical layout.
  max_subgroups_hwrap: 2
  _help_max_pargs_hwrap:
    - If a positional argument group contains more than this many
    - arguments, then force it to a vertical layout.
  max_pargs_hwrap: 2
